name: ClientRPC Validation
on: [push, pull_request]
permissions:
  contents: read

jobs:
  clientrpc:
    name: Check ClientRPC bindings
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.25'
      - name: Check out source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          version: '23.x'
      - name: Install protolint
        run: go install github.com/yoheimuta/protolint/cmd/protolint@v0.47.5
      - name: Lint proto files
        run: protolint lint .
        working-directory: clientrpc
      - name: Rebuild the bindings
        run:  ./regen-clientrpc.sh
        working-directory: clientrpc
      - name: Verify rebuilding is not dirty
        id: changes
        uses: UnicornGlobal/has-changes-action@ea00e6f831a9e785271645729fa251907b314707 #v1.0.12
      - name: Fail if there are changes in repo
        if: steps.changes.outputs.changed == 1
        run: exit 1

